name: "my_first-action_pipline"

on: workflow_dispatch
permissions:
  id-token: write
  contents: read
jobs:
  terraform-init-plan:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        
   
